// Generated by CoffeeScript 1.3.1
(function() {
  var Monglow,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  var Mongolian = require("mongolian");
  var MonglowModel = require("./model");
  var MonglowRelation = require("./relation");

  Monglow = (function() {

    Monglow.name = 'Monglow';

    function Monglow(server_string) {
      this.server_string = server_string;
    }

    Monglow.prototype.connect = function(server_string) {
      if (this.connected(server_string)) {
        return this.Client;
      }
      if (server_string) {
        this.server_string = server_string;
      }
      if (!this.server_string) {
        this.server_string = "mongo://127.0.0.1:27017/monglow_test";
      }
      return this.Client = new Mongolian(this.server_string);
    };

    Monglow.prototype.connected = function(server_string) {
      return this.Client && (typeof server_string === "undefined" || server_string === this.server_string);
    };

    Monglow.prototype.close = function() {
      return this.Client.close();
    };

    Monglow.prototype.model = function(name, options) {
      var Model, model_name, that;
      that = this;
      model_name = name;
      Model = (function(_super) {

        __extends(Model, _super);

        Model.name = 'Model';

        Model.model_name = name;

        Model.client = that.Client;

        Model.model = Model;

        if (options) {
          Model.references_many = options.references_many;
        }

        function Model(params) {
          var name, ref, value, _i, _len, _ref;
          this.model_name = model_name;
          this.client = that.Client;
          if (options) {
            this.references_many = options.references_many;
          }
          if (this.references_many) {
            _ref = this.references_many;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              ref = _ref[_i];
              this[ref] = new MonglowRelation;
              Object.defineProperty(this, ref, {
                enumerable: false
              });
            }
          }
          for (name in params) {
            value = params[name];
            if (!this[name]) {
              this[name] = value;
            }
          }
          Model.__super__.constructor.call(this, params);
        }

        return Model;

      })(MonglowModel);
      Object.defineProperty(Model.prototype, 'constructor', {
        enumerable: false
      });
      return Model;
    };

    return Monglow;

  })();

  module.exports = new Monglow;

}).call(this);
